/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as AcademyIndexRouteImport } from './routes/academy/index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AcademyRagRouteImport } from './routes/academy/rag'
import { Route as AcademyPythonForAiRouteImport } from './routes/academy/python-for-ai'
import { Route as AcademyPromptEngineeringRouteImport } from './routes/academy/prompt-engineering'
import { Route as AcademyMcpRouteImport } from './routes/academy/mcp'
import { Route as AcademyGenerativeAiRouteImport } from './routes/academy/generative-ai'
import { Route as AcademyDeepLearningRouteImport } from './routes/academy/deep-learning'
import { Route as AcademyCorporateTrainingRouteImport } from './routes/academy/corporate-training'
import { Route as AcademyAiTrainingRouteImport } from './routes/academy/ai-training'
import { Route as AcademyAiAgentsRouteImport } from './routes/academy/ai-agents'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const AcademyRagRoute = AcademyRagRouteImport.update({
  id: '/academy/rag',
  path: '/academy/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyPythonForAiRoute = AcademyPythonForAiRouteImport.update({
  id: '/academy/python-for-ai',
  path: '/academy/python-for-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyPromptEngineeringRoute =
  AcademyPromptEngineeringRouteImport.update({
    id: '/academy/prompt-engineering',
    path: '/academy/prompt-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyMcpRoute = AcademyMcpRouteImport.update({
  id: '/academy/mcp',
  path: '/academy/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyGenerativeAiRoute = AcademyGenerativeAiRouteImport.update({
  id: '/academy/generative-ai',
  path: '/academy/generative-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyDeepLearningRoute = AcademyDeepLearningRouteImport.update({
  id: '/academy/deep-learning',
  path: '/academy/deep-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCorporateTrainingRoute =
  AcademyCorporateTrainingRouteImport.update({
    id: '/academy/corporate-training',
    path: '/academy/corporate-training',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademyAiTrainingRoute = AcademyAiTrainingRouteImport.update({
  id: '/academy/ai-training',
  path: '/academy/ai-training',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAiAgentsRoute = AcademyAiAgentsRouteImport.update({
  id: '/academy/ai-agents',
  path: '/academy/ai-agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/ai-agents': typeof AcademyAiAgentsRoute
  '/academy/ai-training': typeof AcademyAiTrainingRoute
  '/academy/corporate-training': typeof AcademyCorporateTrainingRoute
  '/academy/deep-learning': typeof AcademyDeepLearningRoute
  '/academy/generative-ai': typeof AcademyGenerativeAiRoute
  '/academy/mcp': typeof AcademyMcpRoute
  '/academy/prompt-engineering': typeof AcademyPromptEngineeringRoute
  '/academy/python-for-ai': typeof AcademyPythonForAiRoute
  '/academy/rag': typeof AcademyRagRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/ai-agents': typeof AcademyAiAgentsRoute
  '/academy/ai-training': typeof AcademyAiTrainingRoute
  '/academy/corporate-training': typeof AcademyCorporateTrainingRoute
  '/academy/deep-learning': typeof AcademyDeepLearningRoute
  '/academy/generative-ai': typeof AcademyGenerativeAiRoute
  '/academy/mcp': typeof AcademyMcpRoute
  '/academy/prompt-engineering': typeof AcademyPromptEngineeringRoute
  '/academy/python-for-ai': typeof AcademyPythonForAiRoute
  '/academy/rag': typeof AcademyRagRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/academy': typeof AcademyIndexRoute
  '/insights': typeof InsightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/insights': typeof InsightsRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/ai-agents': typeof AcademyAiAgentsRoute
  '/academy/ai-training': typeof AcademyAiTrainingRoute
  '/academy/corporate-training': typeof AcademyCorporateTrainingRoute
  '/academy/deep-learning': typeof AcademyDeepLearningRoute
  '/academy/generative-ai': typeof AcademyGenerativeAiRoute
  '/academy/mcp': typeof AcademyMcpRoute
  '/academy/prompt-engineering': typeof AcademyPromptEngineeringRoute
  '/academy/python-for-ai': typeof AcademyPythonForAiRoute
  '/academy/rag': typeof AcademyRagRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/academy/': typeof AcademyIndexRoute
  '/insights/': typeof InsightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/services'
    | '/sitemap.xml'
    | '/academy/ai-agents'
    | '/academy/ai-training'
    | '/academy/corporate-training'
    | '/academy/deep-learning'
    | '/academy/generative-ai'
    | '/academy/mcp'
    | '/academy/prompt-engineering'
    | '/academy/python-for-ai'
    | '/academy/rag'
    | '/insights/$slug'
    | '/academy/'
    | '/insights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/services'
    | '/sitemap.xml'
    | '/academy/ai-agents'
    | '/academy/ai-training'
    | '/academy/corporate-training'
    | '/academy/deep-learning'
    | '/academy/generative-ai'
    | '/academy/mcp'
    | '/academy/prompt-engineering'
    | '/academy/python-for-ai'
    | '/academy/rag'
    | '/insights/$slug'
    | '/academy'
    | '/insights'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/industries'
    | '/insights'
    | '/services'
    | '/sitemap.xml'
    | '/academy/ai-agents'
    | '/academy/ai-training'
    | '/academy/corporate-training'
    | '/academy/deep-learning'
    | '/academy/generative-ai'
    | '/academy/mcp'
    | '/academy/prompt-engineering'
    | '/academy/python-for-ai'
    | '/academy/rag'
    | '/insights/$slug'
    | '/academy/'
    | '/insights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AcademyAiAgentsRoute: typeof AcademyAiAgentsRoute
  AcademyAiTrainingRoute: typeof AcademyAiTrainingRoute
  AcademyCorporateTrainingRoute: typeof AcademyCorporateTrainingRoute
  AcademyDeepLearningRoute: typeof AcademyDeepLearningRoute
  AcademyGenerativeAiRoute: typeof AcademyGenerativeAiRoute
  AcademyMcpRoute: typeof AcademyMcpRoute
  AcademyPromptEngineeringRoute: typeof AcademyPromptEngineeringRoute
  AcademyPythonForAiRoute: typeof AcademyPythonForAiRoute
  AcademyRagRoute: typeof AcademyRagRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/academy/rag': {
      id: '/academy/rag'
      path: '/academy/rag'
      fullPath: '/academy/rag'
      preLoaderRoute: typeof AcademyRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/python-for-ai': {
      id: '/academy/python-for-ai'
      path: '/academy/python-for-ai'
      fullPath: '/academy/python-for-ai'
      preLoaderRoute: typeof AcademyPythonForAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/prompt-engineering': {
      id: '/academy/prompt-engineering'
      path: '/academy/prompt-engineering'
      fullPath: '/academy/prompt-engineering'
      preLoaderRoute: typeof AcademyPromptEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/mcp': {
      id: '/academy/mcp'
      path: '/academy/mcp'
      fullPath: '/academy/mcp'
      preLoaderRoute: typeof AcademyMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/generative-ai': {
      id: '/academy/generative-ai'
      path: '/academy/generative-ai'
      fullPath: '/academy/generative-ai'
      preLoaderRoute: typeof AcademyGenerativeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/deep-learning': {
      id: '/academy/deep-learning'
      path: '/academy/deep-learning'
      fullPath: '/academy/deep-learning'
      preLoaderRoute: typeof AcademyDeepLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/corporate-training': {
      id: '/academy/corporate-training'
      path: '/academy/corporate-training'
      fullPath: '/academy/corporate-training'
      preLoaderRoute: typeof AcademyCorporateTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/ai-training': {
      id: '/academy/ai-training'
      path: '/academy/ai-training'
      fullPath: '/academy/ai-training'
      preLoaderRoute: typeof AcademyAiTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/ai-agents': {
      id: '/academy/ai-agents'
      path: '/academy/ai-agents'
      fullPath: '/academy/ai-agents'
      preLoaderRoute: typeof AcademyAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  InsightsRoute: InsightsRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AcademyAiAgentsRoute: AcademyAiAgentsRoute,
  AcademyAiTrainingRoute: AcademyAiTrainingRoute,
  AcademyCorporateTrainingRoute: AcademyCorporateTrainingRoute,
  AcademyDeepLearningRoute: AcademyDeepLearningRoute,
  AcademyGenerativeAiRoute: AcademyGenerativeAiRoute,
  AcademyMcpRoute: AcademyMcpRoute,
  AcademyPromptEngineeringRoute: AcademyPromptEngineeringRoute,
  AcademyPythonForAiRoute: AcademyPythonForAiRoute,
  AcademyRagRoute: AcademyRagRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
